/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCatatRouteImport } from './routes/_authenticated/catat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDompetRouteImport } from './routes/_authenticated/dompet'
import { Route as AuthenticatedKotakMasukRouteImport } from './routes/_authenticated/kotak-masuk'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatatRoute = AuthenticatedCatatRouteImport.update({
  id: '/catat',
  path: '/catat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDompetRoute = AuthenticatedDompetRouteImport.update({
  id: '/dompet',
  path: '/dompet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKotakMasukRoute = AuthenticatedKotakMasukRouteImport.update({
  id: '/kotak-masuk',
  path: '/kotak-masuk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catat': typeof AuthenticatedCatatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dompet': typeof AuthenticatedDompetRoute
  '/kotak-masuk': typeof AuthenticatedKotakMasukRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catat': typeof AuthenticatedCatatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dompet': typeof AuthenticatedDompetRoute
  '/kotak-masuk': typeof AuthenticatedKotakMasukRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/catat': typeof AuthenticatedCatatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dompet': typeof AuthenticatedDompetRoute
  '/_authenticated/kotak-masuk': typeof AuthenticatedKotakMasukRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/catat'
    | '/dashboard'
    | '/dompet'
    | '/kotak-masuk'
    | '/laporan'
    | '/profil'
    | '/riwayat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/catat'
    | '/dashboard'
    | '/dompet'
    | '/kotak-masuk'
    | '/laporan'
    | '/profil'
    | '/riwayat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/catat'
    | '/_authenticated/dashboard'
    | '/_authenticated/dompet'
    | '/_authenticated/kotak-masuk'
    | '/_authenticated/laporan'
    | '/_authenticated/profil'
    | '/_authenticated/riwayat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catat': {
      id: '/_authenticated/catat'
      path: '/catat'
      fullPath: '/catat'
      preLoaderRoute: typeof AuthenticatedCatatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dompet': {
      id: '/_authenticated/dompet'
      path: '/dompet'
      fullPath: '/dompet'
      preLoaderRoute: typeof AuthenticatedDompetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kotak-masuk': {
      id: '/_authenticated/kotak-masuk'
      path: '/kotak-masuk'
      fullPath: '/kotak-masuk'
      preLoaderRoute: typeof AuthenticatedKotakMasukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCatatRoute: typeof AuthenticatedCatatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDompetRoute: typeof AuthenticatedDompetRoute
  AuthenticatedKotakMasukRoute: typeof AuthenticatedKotakMasukRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCatatRoute: AuthenticatedCatatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDompetRoute: AuthenticatedDompetRoute,
  AuthenticatedKotakMasukRoute: AuthenticatedKotakMasukRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
